# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'class_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassWindow(object):
    def setupUi(self, ClassWindow):
        ClassWindow.setObjectName("ClassWindow")
        ClassWindow.resize(304, 344)
        self.centralwidget = QtWidgets.QWidget(ClassWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(63, 30, 81, 18))
        self.label1.setObjectName("label1")
        self.process = QtWidgets.QPushButton(self.centralwidget)
        self.process.setGeometry(QtCore.QRect(100, 305, 99, 28))
        self.process.setObjectName("process")
        self.p1 = QtWidgets.QComboBox(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(165, 30, 94, 24))
        self.p1.setObjectName("p1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(49, 80, 91, 18))
        self.label2.setObjectName("label2")
        self.p2 = QtWidgets.QTextEdit(self.centralwidget)
        self.p2.setGeometry(QtCore.QRect(165, 80, 94, 24))
        self.p2.setObjectName("p2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(80, 130, 71, 20))
        self.label3.setObjectName("label3")
        self.p3 = QtWidgets.QTextEdit(self.centralwidget)
        self.p3.setGeometry(QtCore.QRect(165, 130, 94, 24))
        self.p3.setObjectName("p3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(34, 180, 101, 20))
        self.label4.setObjectName("label4")
        self.p4 = QtWidgets.QTextEdit(self.centralwidget)
        self.p4.setGeometry(QtCore.QRect(165, 180, 94, 24))
        self.p4.setObjectName("p4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(63, 230, 71, 20))
        self.label5.setObjectName("label5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 260, 171, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(230, 260, 31, 24))
        self.toolButton.setObjectName("toolButton")
        ClassWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClassWindow)
        QtCore.QMetaObject.connectSlotsByName(ClassWindow)

    def retranslateUi(self, ClassWindow):
        _translate = QtCore.QCoreApplication.translate
        ClassWindow.setWindowTitle(_translate("ClassWindow", "地貌识别"))
        self.label1.setText(_translate("ClassWindow", "算法选择："))
        self.process.setText(_translate("ClassWindow", "开始执行"))
        self.label2.setText(_translate("ClassWindow", "像素块大小："))
        self.label3.setText(_translate("ClassWindow", "紧凑性："))
        self.label4.setText(_translate("ClassWindow", "制图窗口大小："))
        self.label5.setText(_translate("ClassWindow", "保存路径："))
        self.toolButton.setText(_translate("ClassWindow", "..."))
