# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'class_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassWindow(object):
    def setupUi(self, ClassWindow):
        ClassWindow.setObjectName("ClassWindow")
        ClassWindow.resize(325, 357)
        self.centralwidget = QtWidgets.QWidget(ClassWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(60, 30, 81, 18))
        self.label1.setObjectName("label1")
        self.processButton = QtWidgets.QPushButton(self.centralwidget)
        self.processButton.setGeometry(QtCore.QRect(110, 310, 99, 28))
        self.processButton.setObjectName("processButton")
        self.p_type = QtWidgets.QComboBox(self.centralwidget)
        self.p_type.setGeometry(QtCore.QRect(162, 30, 131, 24))
        self.p_type.setObjectName("p_type")
        self.p_type.addItem("")
        self.p_type.addItem("")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(46, 80, 91, 18))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(77, 130, 71, 20))
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(31, 180, 101, 20))
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(60, 230, 71, 20))
        self.label5.setObjectName("label5")
        self.p_sp = QtWidgets.QLineEdit(self.centralwidget)
        self.p_sp.setGeometry(QtCore.QRect(47, 260, 211, 24))
        self.p_sp.setObjectName("p_sp")
        self.saveButton = QtWidgets.QToolButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(264, 260, 31, 24))
        self.saveButton.setObjectName("saveButton")
        self.p_super = QtWidgets.QLineEdit(self.centralwidget)
        self.p_super.setGeometry(QtCore.QRect(162, 80, 131, 24))
        self.p_super.setObjectName("p_super")
        self.p_m = QtWidgets.QLineEdit(self.centralwidget)
        self.p_m.setGeometry(QtCore.QRect(162, 130, 131, 24))
        self.p_m.setObjectName("p_m")
        self.p_winsize = QtWidgets.QLineEdit(self.centralwidget)
        self.p_winsize.setGeometry(QtCore.QRect(162, 180, 131, 24))
        self.p_winsize.setObjectName("p_winsize")
        ClassWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClassWindow)
        QtCore.QMetaObject.connectSlotsByName(ClassWindow)

    def retranslateUi(self, ClassWindow):
        _translate = QtCore.QCoreApplication.translate
        ClassWindow.setWindowTitle(_translate("ClassWindow", "地貌识别"))
        self.label1.setText(_translate("ClassWindow", "数据来源："))
        self.processButton.setText(_translate("ClassWindow", "开始执行"))
        self.p_type.setItemText(0, _translate("ClassWindow", "JezeroCrater"))
        self.p_type.setItemText(1, _translate("ClassWindow", "ZhuRong"))
        self.label2.setText(_translate("ClassWindow", "超像素大小："))
        self.label3.setText(_translate("ClassWindow", "紧凑性："))
        self.label4.setText(_translate("ClassWindow", "制图窗口大小："))
        self.label5.setText(_translate("ClassWindow", "保存路径："))
        self.saveButton.setText(_translate("ClassWindow", "..."))
        self.p_super.setText(_translate("ClassWindow", "65"))
        self.p_m.setText(_translate("ClassWindow", "0.2"))
        self.p_winsize.setText(_translate("ClassWindow", "200"))
