# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(512, 368)
        self.graphicsView = QtWidgets.QGraphicsView(HelpWindow)
        self.graphicsView.setGeometry(QtCore.QRect(40, 10, 441, 301))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(HelpWindow)
        self.label.setGeometry(QtCore.QRect(20, 320, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(HelpWindow)
        self.label_2.setGeometry(QtCore.QRect(140, 320, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(HelpWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 330, 481, 41))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "关于软件"))
        self.label.setText(_translate("HelpWindow", "MarsMapper V1.0"))
        self.label_2.setText(_translate("HelpWindow", "Build 11/11/2025"))
        self.label_3.setText(_translate("HelpWindow", "<html><head/><body><p>Developed by College of Surveying and Geographic Informatics，Tongji University</p></body></html>"))
