# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Imginfo_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImgInfoWindow(object):
    def setupUi(self, ImgInfoWindow):
        ImgInfoWindow.setObjectName("ImgInfoWindow")
        ImgInfoWindow.resize(371, 466)
        self.InfoTab1 = QtWidgets.QTableWidget(ImgInfoWindow)
        self.InfoTab1.setGeometry(QtCore.QRect(20, 40, 331, 191))
        self.InfoTab1.setObjectName("InfoTab1")
        self.InfoTab1.setColumnCount(0)
        self.InfoTab1.setRowCount(0)
        self.InfoTab2 = QtWidgets.QTableWidget(ImgInfoWindow)
        self.InfoTab2.setGeometry(QtCore.QRect(20, 260, 331, 191))
        self.InfoTab2.setObjectName("InfoTab2")
        self.InfoTab2.setColumnCount(0)
        self.InfoTab2.setRowCount(0)
        self.label1 = QtWidgets.QLabel(ImgInfoWindow)
        self.label1.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(ImgInfoWindow)
        self.label2.setGeometry(QtCore.QRect(20, 240, 72, 15))
        self.label2.setObjectName("label2")

        self.retranslateUi(ImgInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(ImgInfoWindow)

    def retranslateUi(self, ImgInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        ImgInfoWindow.setWindowTitle(_translate("ImgInfoWindow", "影像信息"))
        self.label1.setText(_translate("ImgInfoWindow", "基础信息"))
        self.label2.setText(_translate("ImgInfoWindow", "投影信息"))
