# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Preproc_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreprossWin(object):
    def setupUi(self, PreprossWin):
        PreprossWin.setObjectName("PreprossWin")
        PreprossWin.resize(262, 210)
        self.label = QtWidgets.QLabel(PreprossWin)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PreprossWin)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton2 = QtWidgets.QPushButton(PreprossWin)
        self.pushButton2.setGeometry(QtCore.QRect(90, 160, 75, 23))
        self.pushButton2.setObjectName("pushButton2")
        self.lineEdit = QtWidgets.QLineEdit(PreprossWin)
        self.lineEdit.setGeometry(QtCore.QRect(160, 30, 91, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(PreprossWin)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 110, 191, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton1 = QtWidgets.QPushButton(PreprossWin)
        self.pushButton1.setGeometry(QtCore.QRect(220, 110, 31, 23))
        self.pushButton1.setObjectName("pushButton1")

        self.retranslateUi(PreprossWin)
        QtCore.QMetaObject.connectSlotsByName(PreprossWin)

    def retranslateUi(self, PreprossWin):
        _translate = QtCore.QCoreApplication.translate
        PreprossWin.setWindowTitle(_translate("PreprossWin", "灰度拉伸"))
        self.label.setText(_translate("PreprossWin", "<html><head/><body><p>截断百分比(建议0.5)：</p></body></html>"))
        self.label_2.setText(_translate("PreprossWin", "保存路径："))
        self.pushButton2.setText(_translate("PreprossWin", "执行拉伸"))
        self.pushButton1.setText(_translate("PreprossWin", "..."))
