# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImgInfo_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImgInfowindow(object):
    def setupUi(self, ImgInfowindow):
        ImgInfowindow.setObjectName("ImgInfowindow")
        ImgInfowindow.resize(332, 377)

        self.retranslateUi(ImgInfowindow)
        QtCore.QMetaObject.connectSlotsByName(ImgInfowindow)

    def retranslateUi(self, ImgInfowindow):
        _translate = QtCore.QCoreApplication.translate
        ImgInfowindow.setWindowTitle(_translate("ImgInfowindow", "影像信息"))
